/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qiirhtfaskoxuovpriqz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpaXJodGZhc2tveHVvdnByaXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMxNDY3MTYsImV4cCI6MjA5ODcyMjcxNn0.dqVJPUs-J-F2tj80lM47OmaXHIRhYF1Ly96J8Q4-s8c"